name: Validate Client Generation

on:
  workflow_run:
    workflows:
      - 'Spec PR'
    types:
      - completed

jobs:
  validate-client-gen:
    name: Validate client generation

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Check out openapi
        uses: actions/checkout@v2.5.0

      - name: GitHub Checks
        uses: LouisBrunner/checks-action@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Validate Client Generation
          sha: ${{ github.event.workflow_run.head_sha }}
          status: in_progress
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}

      - name: Check out pydo repo
        uses: actions/checkout@v2.5.0
        with:
          repository: digitalocean/pydo
          path: pydo

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.1.13
          virtualenvs-path: .venv
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: false

      - name: Download PR spec
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n openapi-bundled
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Python client
        working-directory: pydo
        run: SPEC_FILE=../openapi-bundled.yaml make generate

      - name: Run Mocked Tests
        id: test-mocked
        working-directory: pydo
        run: make test-mocked

      - name: GitHub Checks
        if: always()
        uses: LouisBrunner/checks-action@v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Validate Client Generation
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: ${{ steps.test-mocked.outcome }}
          status: completed
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
