name: Validate Client Generation

on:
  workflow_run:
    workflows:
      - 'Spec PR'
    types:
      - completed

jobs:
  validate-client-gen:
    name: Validate client generation

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Check out pydo repo
        uses: actions/checkout@v2.5.0
        with:
          repository: digitalocean/pydo

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.1.13
          virtualenvs-path: .venv
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: false

      - name: Download PR spec
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n openapi-bundled
          # workflow_conclusion: success
          # pr: ${{github.event.pull_request.number}}
          # name: openapi-bundled

      - name: Generate Python client
        run: SPEC_FILE=openapi-bundled.yaml make generate
